[package]
name = "node_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
path = "./src/node_macro.rs"

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
node_traits = { path = "../node_traits" }
