import numpy
import numpy.typing

F64NDArray = numpy.typing.NDArray[numpy.float64]

class SineOscillator: ...

class DspGraph:
    def play(self, num_samples: int) -> F64NDArray: ...
    def draw(self) -> bytes: ...
    def add_sine(self, sine: SineOscillator) -> None: ...
