name: Latex CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: Dyplom.tex
          compiler: pdflatex
          args: -interaction=nonstopmode

