name: Latex
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/latex-action@v2
        with:
          root_file: Dyplom.tex
          compiler: pdflatex
          args: -interaction=nonstopmode
          working_directory: latex

  chktex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            bash ./check_latex.sh
