name: Python
on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
            target
          key: cache
      - name: Install dependencies
        run: |
          ./.github/workflows/setup.sh

      - name: Formatting
        run: |
          poetry run black .
          poetry run isort .
          git status

      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: |
            .venv
            target
          key: cache

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
            target
          key: cache
      - name: Install dependencies
        run: |
          ./.github/workflows/setup.sh

      - name: Mypy
        run: |
          poetry run mypy .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
            target
          key: cache
      - name: Install dependencies
        run: |
          ./.github/workflows/setup.sh

      - name: Ruff
        run: |
          poetry run ruff .

  dsp_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
            target
          key: cache
      - name: Install dependencies
        run: |
          ./.github/workflows/setup.sh

      - name: Run luthier/dsp.py
        run: |
          poetry run python luthier/dsp.py

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
            target
          key: cache
      - name: Install dependencies
        run: |
          ./.github/workflows/setup.sh
      - name: Run pytest
        run: |
          poetry run pytest .
