name: Python
on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cached virtualenv
        id: venv-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
          key: venv

      - name: Formatting
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run black .
          poetry run isort .
          git status

      - name: Cache virtualenv
        id: venv-save
        uses: actions/cache/save@v3
        with:
          path: |
            .venv
          key: venv

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached virtualenv
        id: venv-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
          key: venv

      - name: Mypy
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run mypy .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached virtualenv
        id: venv-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
          key: venv

      - name: Ruff
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run ruff .

  notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached virtualenv
        id: venv-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
          key: venv

      - name: Run notebook
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          sudo apt install -y graphviz
          poetry run ipython prototyping.ipynb

  dsp_py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Restore cached virtualenv
        id: venv-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            .venv
          key: venv

      - name: Run dsp.py
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          sudo apt install -y graphviz ffmpeg
          poetry run python dsp.py

