name: Python
on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run black .
          poetry run isort .
          git status

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Mypy
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run mypy .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Ruff
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run ruff .

  notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run notebook
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          sudo apt install -y graphviz
          poetry run ipython prototyping.ipynb



