name: Python
on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run black .
          git status

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run mypy .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
          poetry run ruff .
