name: Rust
on: [push]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Check format
        run: |
          cargo fmt --check

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: |
          sudo apt install libasound2-dev
          cargo build --all-targets --all-features --examples --workspace

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: |
          sudo apt install libasound2-dev
          cargo clippy --all-targets --all-features --examples --workspace

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Test
        run: |
          sudo apt install libasound2-dev graphviz
          cargo test --workspace
